# -*- coding: utf-8 -*-
"""fake_news.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dei7OWv9-_KzRMvyK3aj2xpcIwitPWYR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score, confusion_matrix, classification_report

data1 = pd.read_csv("True.csv")
data2 = pd.read_csv("Fake.csv")

print(data1.isnull().sum)
data1.head()

print(data2.isnull().sum)
data2.head()

data1["label"] = 1   #real
data2["label"] = 0   #fake

data = pd.concat([data1,data2], ignore_index=True) #combine the data
data.head()

data = data.sample(frac=1).reset_index(drop=True) #shuffle the rows
data.head()

import nltk                                              # Natural Language Toolkit
nltk.download('stopwords')                               #Words like "the", "is", "was" that don’t add much meaning.
nltk.download('wordnet')                                 #Helps us with lemmatization

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer           #Brings words down to their root (running - run)

import re
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()                                                                             #Lowercase all text: "This is News" → "this is news"
    text = re.sub('[^a-zA-Z]', ' ', text)                                                           #Remove punctuation/numbers: keep only letters
    words = text.split()                                                                            #Split into words (tokenization): "this is news" → ["this", "is", "news"]
    words = [lemmatizer.lemmatize(w) for w in words if w not in stop_words]                         #Remove stopwords + lemmatize
    return " ".join(words)                                                                          #Join cleaned words back into a sentence

data['clean_text'] = data['text'].apply(clean_text)      # making a different col for the clean text
data.head()

data[['text', 'clean_text']].head()

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(data['clean_text'])
y = data['label']

data.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

from sklearn.linear_model import LogisticRegression

model= LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("accuracy score", accuracy_score(y_test, y_pred))
print("confusion matrix", confusion_matrix(y_test, y_pred))
print("classification report", classification_report(y_test, y_pred))

# test data

def predict_news(news_text):
    cleaned = clean_text(news_text)
    vec = vectorizer.transform([cleaned])
    prediction = model.predict(vec)
    return "REAL" if prediction[0] == 1 else "FAKE"

predict_news("Government announces major tax cuts for middle class.")

predict_news("Elon Musk buys the moon to build SpaceTesla.")